# Generated by Django 4.0.6 on 2022-08-01 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uvs', '0002_alter_uv_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uv',
            name='price',
            field=models.DecimalField(decimal_places=3, max_digits=4),
        ),
    ]
